theme: jekyll-theme-slate
not_a_password: "98675(*&^kjfLIJYG"
token: "HCP-98075KUYFkluyfg(&*^%7^r&65i7f"
one_password: "97865IUYRFkuyf(*&^$%i76iU7%5 "
two_password: "98765(*&^%ouiytfgOKLUYF"
hcp_token: "HCP-24357-3457-sdtghj-KIUYF-34567"
secret_token: "ghp_dTfDdA47KjeYLh3KGFU33INCveNodl94mdk7"
foo: "bar"
